# Polish translation for openobject-addons
# Copyright (c) 2012 Rosetta Contributors and Canonical Ltd 2012
# This file is distributed under the same license as the openobject-addons package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012.
#
msgid ""
msgstr ""
"Project-Id-Version: openobject-addons\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2012-02-08 00:36+0000\n"
"PO-Revision-Date: 2012-11-02 14:31+0000\n"
"Last-Translator: Łukasz Cieśluk <lukaszciesluk@gmail.com>\n"
"Language-Team: Polish <pl@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2012-11-03 05:28+0000\n"
"X-Generator: Launchpad (build 16218)\n"

#. module: google_base_account
#: field:res.users,gmail_user:0
msgid "Username"
msgstr ""

#. module: google_base_account
#: model:ir.actions.act_window,name:google_base_account.act_google_login_form
msgid "Google Login"
msgstr ""

#. module: google_base_account
#: code:addons/google_base_account/wizard/google_login.py:29
#, python-format
msgid "Google Contacts Import Error!"
msgstr ""

#. module: google_base_account
#: view:res.users:0
msgid " Synchronization "
msgstr ""

#. module: google_base_account
#: sql_constraint:res.users:0
msgid "You can not have two users with the same login !"
msgstr ""

#. module: google_base_account
#: code:addons/google_base_account/wizard/google_login.py:75
#, python-format
msgid "Error"
msgstr ""

#. module: google_base_account
#: view:google.login:0
msgid "Google login"
msgstr ""

#. module: google_base_account
#: model:ir.model,name:google_base_account.model_res_users
msgid "res.users"
msgstr "res.users"

#. module: google_base_account
#: field:google.login,password:0
msgid "Google Password"
msgstr ""

#. module: google_base_account
#: view:google.login:0
msgid "_Cancel"
msgstr ""

#. module: google_base_account
#: view:res.users:0
msgid "Google Account"
msgstr ""

#. module: google_base_account
#: field:google.login,user:0
msgid "Google Username"
msgstr ""

#. module: google_base_account
#: code:addons/google_base_account/wizard/google_login.py:29
#, python-format
msgid ""
"Please install gdata-python-client from http://code.google.com/p/gdata-"
"python-client/downloads/list"
msgstr ""
"Zainstaluj gdata-python-client z http://code.google.com/p/gdata-python-"
"client/downloads/list"

#. module: google_base_account
#: model:ir.model,name:google_base_account.model_google_login
msgid "Google Contact"
msgstr ""

#. module: google_base_account
#: view:google.login:0
msgid "_Login"
msgstr ""

#. module: google_base_account
#: constraint:res.users:0
msgid "The chosen company is not in the allowed companies for this user"
msgstr ""

#. module: google_base_account
#: field:res.users,gmail_password:0
msgid "Password"
msgstr ""

#. module: google_base_account
#: code:addons/google_base_account/wizard/google_login.py:75
#, python-format
msgid "Authentication fail check the user and password !"
msgstr ""

#. module: google_base_account
#: view:google.login:0
msgid "ex: user@gmail.com"
msgstr "np: user@gmail.com"
